name: 'Close stale issues'
on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 30
          any-of-labels: needs-info
          labels-to-remove-when-unstale: needs-info
